### ISSUE TITLE
Failed to resolve entry for package "@jaimebboyjt/tres-fps-controls". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by bperel** [JaimeTorrealba/tres-fps-controls#7]
This error occurs only in version 0.0.53: 0.0.52 and lower are fine.

I use Vite and no custom config.

Full stack:
```
Error:   Failed to scan for dependencies from entries:
  /my/project/index.html

  ✘ [ERROR] Failed to resolve entry for package "@jaimebboyjt/tres-fps-controls". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1225:21:
      1225 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///my/project/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46541:15)
    at resolvePackageEntry (file:///my/project/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46538:3)
    at tryNodeResolve (file:///my/project/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46354:16)
    at ResolveIdContext.resolveId (file:///my/project/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46104:19)
    at PluginContainer.resolveId (file:///my/project/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48919:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///my/project/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49530:22)
    at async file:///my/project/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49692:28
    at async requestCallbacks.on-resolve (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1225:22)
    at async handleRequest (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:647:11)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///my/project/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49680:13)
    at handlePlugins (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1150:21)
    at buildOrContextImpl (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:873:5)
    at Object.buildOrContext (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:699:5)
    at /my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:2032:68
    at new Promise (<anonymous>)
    at Object.context (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:2032:27)
    at Object.context (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1874:58)
    at prepareEsbuildScanner (file:///my/project/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49477:24)

  The plugin "vite:dep-scan" was triggered by this import

    script:/my/project/src/scenes/Menu.vue?id=0:11:28:
      11 │ import { fpsControls } from "@jaimebboyjt/tres-fps-controls";
         ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


    at failureErrorWithLog (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1472:15)
    at /my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:945:25
    at runOnEndCallbacks (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1315:45)
    at buildResponseToResult (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:943:7)
    at /my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:955:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:954:54)
    at handleRequest (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:647:17)
    at handleIncomingPacket (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:672:7)
    at Socket.readFromStdout (/my/project/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:600:7)
```

**Comment by JaimeTorrealba** [comment]
Thanks, I'll check it

**Comment by JaimeTorrealba** [comment]
I don't know how to solve it :(

I think is a problem with the types, I'm not exporting them well, (and the problem start when adding the types)
But honestly I have no idea how :(

**Comment by JaimeTorrealba** [comment]
Solved in 0.0.54
